# Generated by Django 4.0.3 on 2022-07-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.TextField()),
                ('photos_str', models.TextField()),
                ('description', models.TextField()),
                ('temperature', models.CharField(max_length=100)),
                ('care', models.TextField(max_length=100)),
                ('sunlight', models.CharField(max_length=100)),
                ('watering', models.CharField(max_length=100)),
                ('pests', models.TextField(null=True)),
                ('diseases', models.TextField(null=True)),
                ('soil_type', models.TextField(null=True)),
                ('soil_drainage', models.TextField(null=True)),
                ('uses', models.TextField(null=True)),
                ('humidity', models.TextField(null=True)),
                ('fertilizing', models.TextField(null=True)),
            ],
        ),
    ]
